services:
  vue:
    container_name: vue
    build:
      context: ./
      dockerfile: frontend/Dockerfile
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - python

  python:
    container_name: python
    build:
      context: ./
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - PYTHON_ENV=${ENVIRONMENT}
      - DATABASE_URL=${DB_URL}
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_DATABASE: calender
      MYSQL_USER: hjmram
      MYSQL_PASSWORD: j62£6O40{6^1
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: