version: '3.1'

services:
  vue:
    container_name: vue
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:80"

  python:
    container_name: python
    image: python:latest
    working_dir: /app
    volumes:
      - ./backend:/app
    environment:
      - PYTHON_ENV=${ENVIRONMENT}
      - DATABASE_URL=${DB_URL}
    command: ["tail", "-f", "/dev/null"]
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"